// create bikes constant
export const LOCATION_CREATE_REQUEST = 'LOCATION_CREATE_REQUEST'
export const LOCATION_CREATE_SUCCESSFUL = "LOCATION_CREATE_SUCCESSFUL"
export const LOCATION_CREATE_FAIL = "LOCATION_CREATE_FAIL"

//bike fetching
export const LOCATIONS_FETCHING_REQUEST = "LOCATIONS_FETCHING_REQUEST"
export const LOCATIONS_FETCHING_SUCCESSFUL = "LOCATIONS_FETCHING_SUCCESSFUL"
export const LOCATIONS_FETCHING_FAIL = "LOCATIONS_FETCHING_FAIL"

//bike fetching
export const LOCATIONS_APPROVE_FETCHING_REQUEST = "LOCATIONS_APPROVE_FETCHING_REQUEST"
export const LOCATIONS_APPROVE_FETCHING_SUCCESSFUL = "LOCATIONS_APPROVE_FETCHING_SUCCESSFUL"
export const LOCATIONS_APPROVE_FETCHING_FAIL = "LOCATIONS_APPROVE_FETCHING_FAIL"

// single bike fetching
export const LOCATION_FETCHING_REQUEST = "LOCATION_FETCHING_REQUEST"
export const LOCATION_FETCHING_SUCCESSFUL = "LOCATION_FETCHING_SUCCESSFUL"
export const LOCATION_FETCHING_FAIL = "LOCATION_FETCHING_FAIL"

// create bikes constant
export const LOCATION_APPROVAL_REQUEST = 'LOCATION_APPROVAL_REQUEST'
export const LOCATION_APPROVAL_SUCCESSFUL = "LOCATION_APPROVAL_SUCCESSFUL"
export const LOCATION_APPROVAL_FAIL = "LOCATION_APPROVAL_FAIL"

// create bikes constant
export const LOCATION_DISSAPPROVAL_REQUEST = 'LOCATION_DISSAPPROVAL_REQUEST'
export const LOCATION_DISSAPPROVAL_SUCCESSFUL = "LOCATION_DISSAPPROVAL_SUCCESSFUL"
export const LOCATION_DISSAPPROVAL_FAIL = "LOCATION_DISSAPPROVAL_FAIL"

// create bikes constant
export const LOCATION_DELETE_REQUEST = 'LOCATION_DELETE_REQUEST'
export const LOCATION_DELETE_SUCCESSFUL = "LOCATION_DELETE_SUCCESSFUL"
export const LOCATION_DELETE_FAIL = "LOCATION_DELETE_FAIL"